### ISSUE TITLE
extend strong consistency to the process level instead of instance level

### ISSUE THREAD

**Issue by moritzraho** [adobe/aio-lib-state#30]
Currently strong consistency is only supported for operations executed within one state instance (i.e. result of `stateLib.init()`). This behavior is guaranteed by Cosmos DB session consistency model.

This can be easily extended to support strong consistency across instances within the same process by storing the cosmos session id into a static variable when initializing the first instance and reusing the same id for subsequent instances.

**Comment by moritzraho** [comment]
https://docs.microsoft.com/en-us/azure/cosmos-db/how-to-manage-consistency?tabs=portal%2Cdotnetv2%2Capi-async

**Comment by meryllblanchet** [comment]
Handled through a better documentation, see https://github.com/adobe/aio-lib-state#adobe-io-state-store-consistency-guarantees

**Comment by purplecabbage** [comment]
Calling this closed with the doc update.
